steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/anddevil/cogniflow:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/anddevil/cogniflow:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/github.com/anddevil/cogniflow:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
