spring.application.name=cogniflow

# CogniFlow Configuration
cogniflow.alphavantage-api-key=4O2P2O9OFENRBI5M
cogniflow.google-ai-api-key=AIzaSyARZ1LO-6Nhp5k49-8I6sWPF_YRsu-Q2vs
cogniflow.tracked-tickers=IBM,AAPL,MSFT

# Weaviate Configuration
cogniflow.weaviate.host=localhost
cogniflow.weaviate.port=8081
cogniflow.weaviate.scheme=http

# Logging
logging.level.org.springframework.web.client.RestClient=DEBUG

# Resilience4j Circuit Breakers
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

resilience4j.circuitbreaker.instances.alphaVantage.baseConfig=default
resilience4j.circuitbreaker.instances.geminiAi.baseConfig=default
