spring.application.name=cogniflow
# Replace the part after the = with your real key from Alpha Vantage
alphavantage.api.key=NOSA44A0LLTYKZAN

# This helps you see exactly what's happening with the web requests
logging.level.org.springframework.web.client.RestClient=DEBUG

#GEMINI API KEY
google.ai.api.key=AIzaSyCspJkpMGsCZv1EQv1V5iL5VOrHiQF4AGM